source 'https://github.com/CocoaPods/Specs'

xcodeproj 'Hoko Tests'
workspace '../Hoko'

def import_pods
  pod 'OCMock', '~> 3.1.2'
  pod 'OHHTTPStubs', '~> 3.1.10'
  pod 'Expecta', '~> 0.3.2'
  pod 'Hoko', :path => '../'
end

target 'Hoko Tests' do
  platform :ios, '6.0'
  import_pods
end
