source 'https://github.com/CocoaPods/Specs'

xcodeproj 'Hoko Tests'
workspace '../Hoko'
inhibit_all_warnings!

def import_pods
  pod 'OCMock', '~> 3.1.2'
  pod 'OHHTTPStubs', '~> 3.1.10'
  pod 'Expecta', '~> 0.3.2'
  pod 'Hoko', :path => '../'
end

target :ios do
  platform :ios, '6.0'
  link_with 'iOS Tests'
  import_pods
end